### ISSUE TITLE
:sym<> for protoregex actions methods not highlighted

### ISSUE THREAD

**Issue by samcv** [perl6/atom-language-perl6#12]
- [X] Working in `master`

Taken from: https://github.com/MadcapJake/language-perl6fe/issues/32

Issue Description

The :sym<> adverb is specially highlighted on tokens and rules when used inside regexes,
but it's highlighted as a normal name when used in the actions class. It would be useful to highlight it specially there as well:

Example Code
```perl6
grammar Calculator {
    token TOP { <calc-op> }

    proto rule calc-op          {*}
          rule calc-op:sym<add> { <num> '+' <num> }
          rule calc-op:sym<sub> { <num> '-' <num> }

    token num { \d+ }
}

class Calculations {
    method TOP              ($/) { make $<calc-op>.made; }
    method calc-op:sym<add> ($/) { make [+] $<num>; }
    method calc-op:sym<sub> ($/) { make [-] $<num>; }
}

say Calculator.parse('2 + 3', actions => Calculations).made;
```

![0763ff5a-3f78-11e6-9db2-7e76e9306390](https://cloud.githubusercontent.com/assets/20145557/21249119/bc5633a0-c2f0-11e6-93a0-b8ba945959ad.png)
### Leave this in. For internal use.
- [x] Has Tests
- [x] Tests Pass

**Comment by samcv** [comment]
@zoffixznet can we assume if it is a method and we see something like `:sym<\S+>` it is always relating to grammars and should be highlighted the same way the rules are highlighted?

**Comment by zoffixznet** [comment]
> @zoffixznet can we assume if it is a method and we see something like :sym<\S+> it is always relating to grammars and should be highlighted the same way the rules are highlighted?

I think that's a good assumption, since 99.99999999% of code would use it for that reason, despite some rather weird method names being possible:

```perl6
zoffix@VirtualBox:~$ perl6 -e 'class { method foo:bar<ber> { say "hi" } }.new."foo:bar<ber>"()'                                                                                                                                                                
hi
zoffix@VirtualBox:~$ perl6 -e 'class { method foo:::bar<ber> { say "hi" } }.new."foo:::bar<ber>"()'
hi
zoffix@VirtualBox:~$ perl6 -e 'class { method :::<ber> { say "hi" } }.new.":::<ber>"()'                                                                                                                                                                        
hi
zoffix@VirtualBox:~$ 
```

**Comment by samcv** [comment]
Should it only highlight ones with `sym`?

**Comment by zoffixznet** [comment]
Yeah, I think going with just the :sym is fine

**Comment by samcv** [comment]
@zoffixznet the problem should be fixed, but I just want to make sure it doesn't cause any other problems… All the tests pass, but the changes were non-trivial…

Will want this to be tested for at least a few days before the next release.

**Comment by samcv** [comment]
v1.10.0 is released where this is fixed. Closing.
