### ISSUE TITLE
Negative 0* numbers not highlighted same as positive ones

### ISSUE THREAD

**Issue by zoffixznet** [perl6/atom-language-perl6#21]
I'm on v1.11.1

Negative 0* numbers not highlighted same as positive ones

### Example Code
```perl6

say  0xDEADBEEF;
say -0xDEADBEEF;
say  0b010;
say -0b010;
say  0o010;
say -0o010;

```
### Picture [optional]
![untitled](https://cloud.githubusercontent.com/assets/5747918/21295595/80603b7e-c526-11e6-89d9-e56e2555d56e.png)

### Leave this in. For internal use.
- [x] Fixed in Master
- [x] Has Tests
- [x] Passes Tests

**Comment by samcv** [comment]
Fixed in v1.11.2 which is now released. Closing.
