### ISSUE TITLE
Putting a sign on a factional number without whole part makes it not highlight as number

### ISSUE THREAD

**Issue by zoffixznet** [perl6/atom-language-perl6#29]
Putting a +, -, or U+2212 minus on a factional number without whole part makes it not highlight as number

### Example Code
```perl6
    is-deeply pb( '.42', 10),  .42, 'fractional without whole part';
    is-deeply pb('+.42', 10),  .42, 'fractional without whole part with +';
    is-deeply pb('-.42', 10), -.42, 'fractional without whole part with -';
    is-deeply pb('−.42', 10), -.42, 'fractional without whole part with U+2212';
```
### Picture [optional]
![untitled](https://cloud.githubusercontent.com/assets/5747918/21467910/df49a23a-c9ca-11e6-8002-0f566c28b534.png)

### Leave this in. For internal use.
- [x] Fixed in Master
- [x] Has Tests
- [x] Passes Tests

**Comment by samcv** [comment]
@zoffixznet++ just released 1.13.0, where this is fixed. Thanks for reporting this!
