### ISSUE TITLE
Methods are sometimes highlighted as keywords

### ISSUE THREAD

**Issue by japhb** [perl6/atom-language-perl6#33]
As the subject says, methods are sometimes highlighted as keywords.  See these lines taken from https://docs.perl6.org/language/concurrency : 

### Example Code
```perl6
my $p2 = Promise.new;
$p2.break('oh no');

my $promise1 = Promise.in(5);
my $promise2 = $promise1.then(-> $v { say $v.status; 'Second Result' });
say $promise2.result;

my $promise = Promise.start({ die "Broken Promise" });

try $promise2.result;
```

Note how `.break` and `.start` are highlighted differently from `.in`, `.then`, and `.result` -- and the same as `try`.  This is easier to see on docs.perl6.org than on GitHub due to stylesheet differences.

### Leave this in. For internal use.
- [x] Fixed in Master
- [ ] Fixed in Release
- [x] Has Tests
- [x] Passes Tests

**Comment by samcv** [comment]
Fixed in v1.13.7 which has just been released. Closing. Thanks for reporting!
