### ISSUE TITLE
Putting spaces around / division operator breaks highlights

### ISSUE THREAD

**Issue by zoffixznet** [perl6/atom-language-perl6#34]
Putting spaces around / division operator breaks highlights

### Example Code
```perl6
# This block is OK, because 1/4 ain't got spaces between the operator and the numbers
isa-ok(Rat.new(1,4), Rat, "Rat.new makes a Rat");
isa-ok(1/4, Rat, "/ makes a Rat");
isa-ok( 1.Int.Rat, Rat, "cast of Int makes a Rat");
isa-ok( 1.Num.Rat, Rat, "cast of Num makes a Rat");

# This one blows up because there are spaces between 1, /, and 4
isa-ok(Rat.new(1,4), Rat, "Rat.new makes a Rat");
isa-ok(1 / 4, Rat, "/ makes a Rat");
isa-ok( 1.Int.Rat, Rat, "cast of Int makes a Rat");
isa-ok( 1.Num.Rat, Rat, "cast of Num makes a Rat");
```
### Picture [optional]
![untitled](https://cloud.githubusercontent.com/assets/5747918/21544716/8d75fc64-cd9f-11e6-8d74-e7a3c4d8976f.png)

### Leave this in. For internal use.
- [x] Fixed in Master
- [x] Fixed in Release
- [ ] Has Tests
- [ ] Passes Tests

**Comment by samcv** [comment]
It's actually the second `/` on that line that is triggering the bare regex thingy. Will need to figure out the best way to fix this.

**Comment by samcv** [comment]
Tests have now been added. Closing.
