### ISSUE TITLE
Scientific notational numbers with negative exponents not highlighted as numbers

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/atom-language-perl6#35]
### Example Code
```perl6
method Rat(Real:D: Real $epsilon = 1e-6)
```
### Picture
https://docs.perl6.org/type/Duration#(Real)_method_Rat
![screenshot](https://files.progarm.org/2016-12-29-202351_454x124_scrot.png)
### Leave this in. For internal use.
- [ ] Fixed in Master
- [ ] Fixed in Release
- [ ] Has Tests
- [ ] Passes Tests

**Comment by samcv** [comment]
This has been fixed in v1.13.6 which has just been released. Thanks for reporting this!
