### ISSUE TITLE
Variables don't highlight correctly if they contain any non-ASCII characters

### ISSUE THREAD

**Issue by thundergnat** [perl6/atom-language-perl6#36]
> Variables don't highlight correctly if they contain any non-ASCII characters. Pic attached.  Screen shot using Atom editor with Perl 6 FE v1.13.1,  One Dark theme. 

### Example Code
```perl6
$ΔxAB
$ABΔx
$S𝐼
@n⃗
```
### Picture [optional]
![atom-highlight](https://cloud.githubusercontent.com/assets/398208/21565813/452ba3ca-ce6a-11e6-80c2-b3805bdf9ac3.png)

### Leave this in. For internal use.
- [x] Fixed in Master
- [ ] Fixed in Release
- [x] Has Tests
- [x] Passes Tests

**Comment by samcv** [comment]
This has been fixed in v1.13.6 which has just been released. Thanks for reporting this!
