### ISSUE TITLE
Quotes inside angle brakes that aren't assigned to variable break highlighting

### ISSUE THREAD

**Issue by zoffixznet** [perl6/atom-language-perl6#37]
I'm on v1.13.1

### Example Code
```perl6
for <
    $* $" $$ $; $& $` $' $, $. $\ $| $? $@ $]
  $: $= $% $^ $~ @- @+ %- %+ %!
> {
    throws-like "$_ = 1;", X::Syntax::Perl5Var, "Did $_ throw Perl5Var?";
}

# blah blah
```
### Picture [optional]
![untitled](https://cloud.githubusercontent.com/assets/5747918/21580652/a6f5a7fa-cfd6-11e6-898c-cbfcec79763a.png)

### Leave this in. For internal use.
- [x] Fixed in Master
- [x] Fixed in Release
- [ ] Has Tests
- [ ] Passes Tests

**Comment by samcv** [comment]
If you remove the quotes does it highlight fine? Or is it not triggering the angle bracket quoting?

**Comment by samcv** [comment]
Ah I see it's not triggering the angle bracket quoting. Will add for as one of the whitelisted things to allow multi-line. Can you think of any others I should add?

**Comment by zoffixznet** [comment]
No idea.

**Comment by samcv** [comment]
Released a new version, should be fixed now.
