### ISSUE TITLE
Fancy-pants symbols in token:sym<> break highlights

### ISSUE THREAD

**Issue by zoffixznet** [perl6/atom-language-perl6#46]
I'm on 1.13.8

The token with `:sym<💬>` breaks highlights of code that follows it. I also notice that writing it as
```
token statement:sym<💬> {
   <sym> <.ws> <EXPR>
}
```
instead of all on one line as `token statement:sym<💬> { <sym> <.ws> <EXPR> }` avoids the issue.

**EDIT**: but I notice that even in multi-line version, putting a comment inside of it doesn't highlight the comment as the comment

### Example Code
```perl6
    proto token statement {*}
    token statement:sym<EXPR> { <EXPR> }
    token statement:sym<💬> { <sym> <.ws> <EXPR> }
    token statement:sym<fuc> { <sym> }

    proto token sign {*}
    token sign:sym<−> { '−'  }
    token sign:sym<+> { '+'? }

    proto token value {*}
    token value:sym<string> { <?["']> <quote_EXPR: ':q'> }
    token value:sym<integer> { <sign> $<num>=\d+ }
    token value:sym<float>   { <sign> $<num>=[\d+ '.' \d+] }
```
### Picture [optional]
![z](https://cloud.githubusercontent.com/assets/5747918/22334661/8f257f4c-e3a9-11e6-8662-42568267f869.png)

### Leave this in. For internal use.
- [ ] Fixed in Master
- [ ] Fixed in Release
- [ ] Has Tests
- [ ] Passes Tests

**Comment by samcv** [comment]
![screenshot_20170202_014718](https://cloud.githubusercontent.com/assets/20145557/22544424/8b60c4f8-e8e9-11e6-9327-67412707b573.png)

I'm not seeing this issue with the code you provided?
