### ISSUE TITLE
P6 needs a complete repo for configuring Atom as a Perl 6 IDE. 

### ISSUE THREAD

**Issue by tbrowder** [perl6/atom-language-perl6#49]
(Or create another repo in perl6 or add to Atom maybe.)

For example, add any chunks of configuration files or text to be be inserted.  @samcv's .nav marker defs and the nav packag are some good ones to add here:

  https://github.com/0tho/atom-nav-panel-plus
  https://github.com/samcv/dot-files/blob/master/.nav-marker-rules

etc.

### Leave this in. For internal use.
- [ ] Fixed in Master
- [ ] Fixed in Release
- [ ] Has Tests
- [ ] Passes Tests

**Comment by WildYorkies** [comment]
1. Include these extra things with the plugin by default

2. Overhaul the README to include an Installation section and beef up the "How do I use this" section

**Comment by samcv** [comment]
Great suggestion. Will start working on this now.

**Comment by samcv** [comment]
Here is my writeup so far: https://github.com/samcv/Atom-as-a-Perl6-IDE

Let me know your thoughts.

**Comment by WildYorkies** [comment]
@samcv This can probably be closed. I submitted a PR for that repo of yours as well.

**Comment by samcv** [comment]
Have moved that repo here: https://github.com/perl6/Atom-as-a-Perl6-IDE

Closing this issue.
