### ISSUE TITLE
Fully qualified method names not highlighted

### ISSUE THREAD

**Issue by zoffixznet** [perl6/atom-language-perl6#8]
### Issue Description

I'm on v1.9.7

Fully qualified method names not highlighted. I expected them to be highlighted same as normal methods (or fancier).

`.List::perl` in the code below is not highlited.

### Example Code

```perl6
augment class List {
    multi method perl2(List:D:) {
        self.List::perl;
        self.perl;
    }
}

```

### Picture

![z](https://cloud.githubusercontent.com/assets/5747918/21186949/3d521e50-c1e4-11e6-9344-e228db5d6d17.png)

**Comment by samcv** [comment]
Thanks for reporting this :smile: just released v1.9.8 :star:
